import Link from 'next/link';
import Head from 'next/head';

export function MainLayout({ children, title }) {
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav className="wrapper">
				<Link href={'/'}>Home</Link>
				<Link href={'/cities'}>Cities</Link>
				<Link href={'/about'}>About</Link>
			</nav>
			<main className="main">{children}</main>
		</>
	);
}
